string robot_name         # 机器人名字
string camera_name        # 相机名字
uint32 resolution_width   # 图像宽度
uint32 resolution_height  # 图像高度
uint32 fps                #  帧率，默认用10
---
bool success      # 是否启动成功
string infos      # 启动失败时的错误信息




