uint8 CAMERA=0
uint8 VIDEO=1
uint8 IMAGES=2

string robot_name              # 机器人名字
uint8 source_type              # 标定数据源
string video_file_path         # 视频文件路径
string images_folder_path      # 图像文件夹路径
string camera_name             # 相机名字
uint32 resolution_width        # 图像宽度
uint32 resolution_height       # 图像高度
float32 fps                    # 帧率，默认用10
---
bool success               # 是否启动成功
string infos               # 启动失败时的错误信息
string topic_origin        # 原始图像话题
string topic_undistroted   # 校畸变后的图像话题





